### ISSUE TITLE
Add provided data to project

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#1]
Dr. Aurisano has provided the "course-data-1.zip" file in the Project 2 description page on Canvas. This file contains information about each of the demo classes we need to incorporate into our project. We need to add these files to an S3 bucket for our project so that we can incorporate this data into our implementation.

**Comment by nishilfaldu** [comment]
Data added to the S3 Bucket (https://github.com/nishilfaldu/alterna-canvas/pull/26)
<img width="1440" alt="Screenshot 2023-11-01 at 11 12 00 PM" src="https://github.com/nishilfaldu/alterna-canvas/assets/63477134/f6061733-4213-4b52-8475-92f96bb044d3">
