### ISSUE TITLE
Add content/functionality to Assignments tab component

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#11]
Popup modal upon button click for submit
Change content to say how many water drops earned

**Comment by nishilfaldu** [comment]
(1) Assignments Tab
<img width="1365" alt="Screenshot 2023-11-06 at 11 52 08 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/63477134/bbb0e044-e029-4f83-bfc2-7cc35de4e9c2">

(2) Onclick - Assignments Not Submitted
<img width="1374" alt="Screenshot 2023-11-06 at 11 53 35 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/63477134/db334acc-5023-42ad-ba2c-8e49de7a1e82">

(3) On uploading a file
<img width="1114" alt="Screenshot 2023-11-06 at 11 54 18 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/63477134/8685165c-a7b5-4855-a568-fe5bf1c36022">

(4) Onclick - OK after submission of assignment
<img width="784" alt="Screenshot 2023-11-06 at 11 54 41 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/63477134/3cf67b29-3a09-4555-81d8-b66094036141">
