### ISSUE TITLE
Decide on the fonts/colors to be used throughout the app

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#12]

**Comment by AnushaChitranshi** [comment]
<img width="1437" alt="Screen Shot 2023-10-31 at 7 25 22 PM" src="https://github.com/nishilfaldu/alterna-canvas/assets/98443786/f5a4798e-aa38-4adf-a959-fa5c42a2ccf7">

@egardner2019 @nishilfaldu @athulyaganesh How do you all feel about this palette?

**Comment by nishilfaldu** [comment]
Looks amazing!

**Comment by eceja2024** [comment]
I like it, but I worry it's a bit intense (especially the middle one). How about something like one of these?
@AnushaChitranshi @athulyaganesh @nishilfaldu 

![image](https://github.com/nishilfaldu/alterna-canvas/assets/56894514/14e03296-811a-4cd8-80b4-f6ec5dd3e430)
![image](https://github.com/nishilfaldu/alterna-canvas/assets/56894514/13da8f9d-311d-4320-bc0f-51c76de14c6a)

**Comment by athulyaganesh** [comment]
I think I prefer the more muted tones

**Comment by eceja2024** [comment]
Use the regular font and the following colors:
![image](https://github.com/nishilfaldu/alterna-canvas/assets/56894514/339d8c64-74c0-4c5f-bb7d-c59afe40cace)
