### ISSUE TITLE
Create several mock students and associated data

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#18]
From the project description:

> Develop several mock students to show how your UI motivates them to perform better, or celebrates their success.

**Comment by nishilfaldu** [comment]
<img width="1128" alt="Screenshot 2023-11-08 at 1 30 33 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/63477134/89e7c130-d1a3-4f5c-a866-3cd0967f96a4">

Data changes on user change (new PR and a new issue will have to be created to connect the user data to all pages)
