### ISSUE TITLE
Add plant/grades data to JSON file within project

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#20]

**Comment by athulyaganesh** [comment]
JSON data is required for 
1. Plant data 
2. Grade data 
3. To-do data
4. Announcement data

**Comment by nishilfaldu** [comment]
Mock data added for most of the things. Announcements data can have its own file like you already do as they are just common to everyone. Grades are coming from an excel file, as mentioned by @egardner2019 , so I don't think it's worth storing that in json (as we can display grades by just parsing the file). To-do data can be added as a new field in the `users.json` file. Missing something or got anything wrong? let me know!

**Comment by athulyaganesh** [comment]
<img width="1252" alt="Screenshot 2023-11-08 at 10 05 30 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/68687725/f6399a68-b114-48b9-a16c-f5fee0dd71dc">

^^Screenshot of the Excel for the UI Course. Do the points on the first picture indicate how much the student scored or how much it is out of? If its the former then we may have to add in our own data for how much the student scored

**Comment by athulyaganesh** [comment]
<img width="363" alt="Screenshot 2023-11-08 at 1 15 06 PM" src="https://github.com/nishilfaldu/alterna-canvas/assets/68687725/1ce0fbfb-93cf-49b0-918c-0fd2137aefbd">
I went ahead and added the grades for each student. We may not require the bucket for the grades
