### ISSUE TITLE
Ensure consistent design throughout

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#23]
Make sure the pages/tabs follow a similar layout.

**Comment by AnushaChitranshi** [comment]
@egardner2019 I am done with my tasks, I can take this on if you'd like

**Comment by eceja2024** [comment]
> @egardner2019 I am done with my tasks, I can take this on if you'd like

That would be great!

**Comment by athulyaganesh** [comment]
@AnushaChitranshi Plant page is done (s/o Emma for the images), here is a prototype of the page: 

<img width="1470" alt="Screenshot 2023-11-11 at 7 59 01 PM" src="https://github.com/nishilfaldu/alterna-canvas/assets/68687725/fb52aa26-39b7-4ee7-8484-28ef08d12bb8">

**Comment by athulyaganesh** [comment]
<img width="1468" alt="Screenshot 2023-11-11 at 8 03 37 PM" src="https://github.com/nishilfaldu/alterna-canvas/assets/68687725/aaa8ac90-c863-4f7f-b8b1-ce32846f7e58">

**Comment by eceja2024** [comment]
All functionality is complete. I think everything looks uniform, but that's up to you, @AnushaChitranshi!
