### ISSUE TITLE
Hide the metadata folder from users in the Files tab

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#29]
On the Files tab of a course, we are showing all of the files Dr. Aurisano gave us for that course. This isn't ideal, as the user shouldn't see the metadata. We need to decide what we want to show and hide the rest.

**Comment by nishilfaldu** [comment]
I think this is trivial in my opinion. Do you want me to just delete the metadata folder from S3 and call it a day @egardner2019 ?

**Comment by eceja2024** [comment]
@nishilfaldu Please don’t remove them from S3. We need to use those metadata files to determine how to calculate and display grades on the Grades tab. We can’t remove them from S3 because we need a way to access them. Since it’s in the End milestone, let’s only worry about hiding it from the user if we have time.

**Comment by athulyaganesh** [comment]
I have added all the grades data including user score, total possible score and weightage for each type of assessments for all three students and all three courses (in users.json). Please take a look and if that is enough for grades calculation we could get rid of the metadata files. Let me know!

**Comment by eceja2024** [comment]
@nishilfaldu Since we're no longer using the metadata file, if you could please delete it (and the associated folder) from S3, that would be great!
