### ISSUE TITLE
Create the CoursePage component based on prototype

### ISSUE THREAD

**Issue by eceja2024** [nishilfaldu/alterna-canvas#5]
Create the basic UI for an individual course. Add tabs (not showing any of their content).

**Comment by nishilfaldu** [comment]
Refer the PR: https://github.com/nishilfaldu/alterna-canvas/pull/24

**Comment by eceja2024** [comment]
@nishilfaldu Instead of having a .jsx file for each course (Graphics.jsx, SeniorDesign.jsx, and UICourse.jsx), I think we should create an IndividualCourse.jsx that takes in a course name as a parameter and then displays the correct data. It will save us a lot of time in the end and make our project more dynamic. I'm working on a branch/PR for this now.
