### ISSUE TITLE
Add in the garden picture at the bottom of each page for a splash of color (@everyone, thoughts?) 

### ISSUE THREAD

**Issue by athulyaganesh** [nishilfaldu/alterna-canvas#85]

**Comment by eceja2024** [comment]
If I remember correctly, we had discussed this when deciding what would be on each page, and we ruled against it. Personally, I think it looks great as is. I'm worried that adding it to each page will mess up the layouts. But that's just my opinion!

**Comment by athulyaganesh** [comment]
Lemme try it out and put in some screenshots?

**Comment by athulyaganesh** [comment]
<img width="1468" alt="Screenshot 2023-11-12 at 12 01 48 AM" src="https://github.com/nishilfaldu/alterna-canvas/assets/68687725/9accfb86-f03a-4937-9524-619f31ed901f">

I'm neutral towards it honestly but may be a good way to get in the A goal

**Comment by eceja2024** [comment]
Good point. If it's easy enough, go for it!
